In [1]:
s = "Hello machine learning world"

print(s[len(s)-1])

d


In [2]:
print( s[5:23])

 machine learning 


In [3]:
# format 
a = 1
b = 'India'

print("{} is the number {} country in the world".format(b,a))

India is the number 1 country in the world


In [4]:
# continue will not run the next line and it will bypass but after the loop, it will pass into next loop
a = [1,2,3,4,5,6,7,8,9]

for n in a:
    if n % 2 ==0:
        continue
    print(n)
else:
    print("program done")

1
3
5
7
9
program done


 # Numpy 

In [5]:
import numpy as np

# 1D array

In [6]:
# array of 10 elements 
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# dimension of the array
a.ndim

1

In [8]:
# shape of the array
a.shape

(10,)

In [9]:
# length of an array
len(a)

10

# MD array

In [115]:
b = np.array( [ [ 10, 12], [ 5 , 8] ] )
b

array([[10, 12],
       [ 5,  8]])

In [11]:
# shape of matrix :  [rows,columns]
b.shape

(2, 1)

In [12]:
# length of matrix: only show number of rows 
len(b)

2

In [13]:
c = np.array([ [ [4,6], [2,3] ] , [ [8,12], [6,9] ] ])
c

array([[[ 4,  6],
        [ 2,  3]],

       [[ 8, 12],
        [ 6,  9]]])

In [14]:
c.shape

(2, 2, 2)

# more functions

In [15]:

x = np.arange(2, 20, 5) # start, end, step jump 
x

array([ 2,  7, 12, 17])

In [16]:

y = np.linspace(0,1, 5) # start, end , between start and end point
y

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# common arrays 

In [17]:
m = np.zeros( (3,3) )
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
mx = np.ones( (2,2) )
mx

array([[1., 1.],
       [1., 1.]])

# diagonal martix : diagonal are one by deafult

In [19]:


mt = np.eye(3)
mt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
mt.dtype

dtype('float64')

# daigonal matrix : with custom values diagonally

In [21]:

mr = np.diag( [1,2,3,4,5] )
mr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:

mr.dtype

dtype('int64')

# specify and converting datatypes 

In [23]:

mx = np.arange(10, dtype='float64')
mx

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
mx.dtype

dtype('float64')

# acessing matrix

In [25]:

v = np.diag( [1,2,3,4] )
v

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
v[2,2] # row , column

3

In [27]:
v[3,3]

4

In [28]:
# assigning and changing values
v[3,2] = 5
v

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 5, 4]])

# slice and its drawback

In [29]:
z = np.arange(20)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
n = z[ : :5] # start, end, step jump
n

array([ 0,  5, 10, 15])

In [31]:
n[0] = 20

In [32]:
n

array([20,  5, 10, 15])

In [33]:
z # value of z got changed due to same memory storage

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
np.shares_memory(n,z)

True

## to solve above problem, we can use copy

In [35]:
t = np.arange(10)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
k = t[: :2].copy()
k

array([0, 2, 4, 6, 8])

In [37]:
np.shares_memory(k,t)

False

In [38]:
# now we modify as they dont share memory anymore

In [39]:
k[1] = 20
k

array([ 0, 20,  4,  6,  8])

In [40]:
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Above values doesnot change

# arethmetic operations 

In [42]:
t ** 2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [43]:
# adding to each values of a matirx

bx = np.ones((4,4)) + 7
bx

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

# matrix multiplication 

In [44]:

qx = np.diag([1,2,3,4])
qx.dot(qx)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

# comparison 

In [45]:
wx = np.arange(5)
ex = np.arange(0,10,2)

In [46]:
wx==ex   # same position value is compared between two matrix 

array([ True, False, False, False, False])

In [47]:
wx > ex

array([False, False, False, False, False])

In [48]:
# alternative built in method 

np.array_equal(wx, ex)

False

# trogonometry values

In [49]:
rx = np.array([0,1,2,3,4,5])

In [50]:
np.sin(rx)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [51]:
np.log(rx)

/Users/somnathpaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [52]:
np.exp(rx)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [53]:
np.tan(rx)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501])

# sum 

In [54]:
tx = np.arange(10)

In [55]:
np.sum(tx)

45

In [56]:
yx = np.array([ [2,3], [4,5] ] )

In [57]:
np.sum(yx, axis=0) # axis  = 0. : column wise addition

array([6, 8])

In [58]:
np.sum(yx, axis=1) # axis = 1: row wise addition

array([5, 9])

# other computation 

In [59]:
ux = np.array( [1,-2,3,4,5,87,9] )


In [60]:
np.min(ux)

-2

In [61]:
np.max(ux)

87

In [62]:
np.argmin(ux) # return the index of minimum value

1

In [63]:
np.argmax(ux) # return the index of max value

5

In [64]:
np.median(ux)

4.0

In [65]:
np.mean(ux)

15.285714285714286

In [66]:
np.std(ux)

29.445903356660597

In [67]:
ix = np.array([2,3,4,5,6])
ox = np.array([2,3,4,5,6])
px = np.array([5,6,7,9,10])


( (ix<=ox) & (ox<=px) ).all()

True

# Broadcasting

### Copying rows of list into no time times in rows and columns 

In [78]:
px = np.array([1,4,8,9])

mtx = np.tile(np.array(px), (3,1)) # 3 copy rows  and 1 copy of column
print(mtx)

[[1 4 8 9]
 [1 4 8 9]
 [1 4 8 9]]


In [79]:
mtx.T  # transpose 

array([[1, 1, 1],
       [4, 4, 4],
       [8, 8, 8],
       [9, 9, 9]])

# converting 1d array into 2d matrix

In [85]:
zx = np.arange(0,20,3)
zx.shape

(7,)

In [92]:
zx = zx[:, np.newaxis]
zx.shape

(7, 1)

In [93]:
zx

array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])

# Flattening 

In [117]:
pox = np.array( [ [ 10, 12, 12], [ 5 , 8, 12] ] )
pox

array([[10, 12, 12],
       [ 5,  8, 12]])

In [118]:
pox.ravel()


array([10, 12, 12,  5,  8, 12])

# Reshape

In [121]:
pox.reshape((3,2))

array([[10, 12],
       [12,  5],
       [ 8, 12]])

# fancy indexing

In [130]:
hx = np.array( [ [1,9,2,4], [2,0,9,6] ] )
hx

array([[1, 9, 2, 4],
       [2, 0, 9, 6]])

In [131]:
jx = np.argsort(hx)  # returns the index of the values inside a list
jx

array([[0, 2, 3, 1],
       [1, 0, 3, 2]])